{{- range $.Values.nodes.masters }}
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: {{ $.Values.cluster.name }}-{{ .site }}-{{ .name }}-{{ $.Values.cluster.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    # InfraEnv to use
    infraenvs.agent-install.openshift.io: "infraenv-{{ $.Values.cluster.name }}"
  annotations:
    bmac.agent-install.openshift.io/role: {{ .role | default "worker" }}
    bmac.agent-install.openshift.io/hostname: "{{ .name }}"
    inspect.metal3.io: disabled
spec:
  online: true
{{- range $index, $int := .interfaces }}
  {{- if eq $index 0 }}  
  bootMACAddress: {{ $int.mac }}
  {{- end }}
{{- end }}
  automatedCleaningMode: disabled
  # Depricated
  hardwareProfile: libvirt
  rootDeviceHints: 
    deviceName: {{ .boot_dev_hint | quote }}
  #  rotational: {{ .boot_spinner_hint }}
  bmc:
    address: {{ .bmc_address }}
    credentialsName: bmc-{{ $.Values.cluster.name }}-{{ .site }}-{{ .name }}
    disableCertificateVerification: True
---
{{- end }}
