{{- range $.Values.nodes.masters }}
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-{{ $.Values.cluster.name }}-{{ .site }}-{{ .name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    cluster-name: {{ $.Values.cluster.name }}-nmstate
spec:
  config:
    interfaces:
{{- if eq (toString .bond_enable) "true" }}
  {{- range $index, $int := .interfaces }}
    {{- if eq $index 0 }}  
      - name: {{ .bond_name }}
        type: bond
        state: up
        mtu: {{ .int_mtu }}
        ipv6:
          enabled: false
        ipv4:
          enabled: true
          address:
            - ip: {{ .IP }}
              prefix-length: {{ .prefix_length }}
          dhcp: false
        link-aggregation:
          mode: {{ .bond_mode }}
          options:
            miimon: '150'
            primary: {{ $int.name | quote }}
          slaves:
    {{- end -}}
    {{- if lt $index (int (toString (.bond_members))) }}  
          - {{ $int.name }}
    {{- end -}}
  {{- end -}}
  {{- range $index, $int := .interfaces }}
      - name: {{ $int.name }}
        type: ethernet
    {{- if lt $index (int (toString (.bond_members))) }}  
        state: up
    {{- else }}
        state: down
    {{- end }}
        mtu: {{ .int_mtu }}
        ipv6:
          enabled: false
        ipv4:
          enabled: false
  {{- end }}
{{- else }}
  {{- range $index, $int := .interfaces }}
    {{- if eq $index 0 }}  
      - name: {{ $int.name }}
        type: ethernet
        state: up
        mtu: {{ .int_mtu }}
        ipv6:
          enabled: false
        ipv4:
          enabled: true
          address:
            - ip: {{ .IP }}
              prefix-length: {{ .prefix_length }}
          dhcp: false
    {{- else }}
      - name: {{ $int.name }}
        type: ethernet
        state: down
        mtu: {{ .int_mtu }}
        ipv6:
          enabled: false
        ipv4:
          enabled: false
    {{- end }}
  {{- end }}
{{- end }}
    dns-resolver:
      config:
        server:
          - '{{ $.Values.global.dns }}'
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: {{ $.Values.cluster.default_router }}
{{- if eq (toString .bond_enable) "true" }}
          next-hop-interface: {{ .bond_name }}
{{- else }}
  {{- range $index, $int := .interfaces }}
    {{- if eq $index 0 }}  
          next-hop-interface: {{ $int.name }}
    {{- end }}
  {{- end }}
{{- end }}
  interfaces:
{{- range $index, $int := .interfaces }}
    - name: {{ $int.name | quote }}
      macAddress: {{ $int.mac | quote }}
{{- end }}
{{- end }}
---
