cluster:
  name: ran2
  api_vip: 10.198.7.171
  ingress_vip: 10.198.7.172
  default_router: 10.198.7.129
  clusternetwork: 10.128.0.0/14
  servicenetwork: 172.30.0.0/16
  cluster_labels:
  - ran.openshift.io/test1: 'test label ran2'
  cluster_annotations:
  - kubernetes.io/description: 'test annotation ran2'
  ## Optional override parameters for local cluster
  #################################################
  default_storage_class: "ocs-storagecluster-ceph-rbd"
  ## default_storage_class: "ocs-external-storagecluster-ceph-rbd"
  #ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkn6tx/IfpY1Eb9QVBsr2Q5WHDGSDTbysuW+2OiifkVfrP/0zVjo7pe1bBxUaEID0rWN6CC1VTwS4GX6cZhGr0wlgT8TUN+rHutxL0Tawqy+yTzqYJ+Vfeilz3CfdAt06QJL9sy57RrlsSTIrlU8CijJTght+v57tmWyKDt2mNJL/5WX9PG40mgXqQ+tfFn+cluOc3V+XcK5dx89dS3oD3Wzn/FmTdwKm8+bnZapWBz7YJf3BU5AL+E82vRCIyZ2MnzbjJ33nTgEF/NdKLEPtyp1dT3Lb0mGB8duj0CFtA3u7CwVi/KMp9JdssN3mN8mGtPE+NwYKsbDA1/++jRCqX login'
  #operator_source: redhat-operator-index
nodes:
  masters:
  - name: "m0"
    site: site1
    role: master
    # hint to try and deploy the RHCOS tro the correct disk
    # for given platform including VMs
    boot_dev_hint: /dev/vda
    # set to true if not installing on SSD or NVMe, example spinning HDD
    boot_spinner_hint: false
    lso: "true"
    ocs: "true"
    node_labels:
      kubernetes.io/description: 'test label ran'
    node_annotations:
      kubernetes.io/description: 'test annotation ran'
    # IP will be applied to either the bond interface (if enabled) or the 1st interface in the "interfaces" list
    IP: "10.198.7.173"
    prefix_length: 26
    #Assumes 1st "bond_members" interface(s) in "interface list" forms the bond
    bond_enable: "false"
    bond_name: bond0
    bond_members: "2"
    bond_mode: active-backup
    #
    int_mtu: 9000
    #
    interfaces:
    - name: "enp1s0"
      mac: "52:54:00:11:61:14"
    #
    bmc_username: root
    bmc_password: password
    bmc_address: redfish-virtualmedia+http://10.198.7.135:8080/redfish/v1/Systems/4e1aef8e-ab32-4ebe-bcba-39ef1c443ea5

  - name: "m1"
    site: site1
    role: master
    # hint to try and deploy the RHCOS tro the correct disk
    # for given platform including VMs
    boot_dev_hint: /dev/vda
    # set to true if not installing on SSD or NVMe, example spinning HDD
    boot_spinner_hint: false
    lso: "true"
    ocs: "true"
    node_labels:
      kubernetes.io/description: 'test label ran'
    node_annotations:
      kubernetes.io/description: 'test annotation ran'
    # IP will be applied to either the bond interface (if enabled) or the 1st interface in the "interfaces" list
    IP: "10.198.7.174"
    prefix_length: 26
    #Assumes 1st "bond_members" interface(s) in "interface list" forms the bond
    bond_enable: "false"
    bond_name: bond0
    bond_members: "2"
    bond_mode: active-backup
    #
    int_mtu: 9000
    #
    interfaces:
    - name: "enp1s0"
      mac: "52:54:00:11:61:15"
    #
    bmc_username: root
    bmc_password: password
    bmc_address: redfish-virtualmedia+http://10.198.7.136:8080/redfish/v1/Systems/7a7df888-3bc8-493f-92fb-937f34099257

  - name: "m2"
    site: site1
    role: master
    # hint to try and deploy the RHCOS to the correct disk
    # for given platform including VMs
    boot_dev_hint: /dev/vda
    # set to true if not installing on SSD or NVMe, example spinning HDD
    boot_spinner_hint: false
    lso: "true"
    ocs: "true"
    node_labels:
      kubernetes.io/description: 'test label ran'
    node_annotations:
      kubernetes.io/description: 'test annotation ran'
    # IP will be applied to either the bond interface (if enabled) or the 1st interface in the "interfaces" list
    IP: "10.198.7.175"
    prefix_length: 26
    #Assumes 1st "bond_members" interface(s) in "interface list" forms the bond
    bond_enable: "false"
    bond_name: bond0
    bond_members: "2"
    bond_mode: active-backup
    #
    int_mtu: 9000
    #
    interfaces:
    - name: "enp1s0"
      mac: "52:54:00:11:61:16"
    #
    bmc_username: root
    bmc_password: password
    bmc_address: redfish-virtualmedia+http://10.198.7.137:8080/redfish/v1/Systems/ba1b9a92-8248-4fe4-8031-5c6217f6bd99
