node:
  site: site2
  name: "du20"
  role: worker
  technology: 5gmmw
  net_function: du_001
  hw_profile: lenovo-sr650
  # hint to try and deploy the RHCOS tro the correct disk
  # for given platform including VMs
  boot_dev_hint: /dev/sdd
  # set to true if not installing on SSD or NVMe, example spinning HDD
  boot_spinner_hint: false
  lso: "true"
  ocs: "false"
  node_labels:
    ran.openshift.io/sriov: ''
    ran.openshift.io/oran-fh-vfio: ''
    ran.openshift.io/oran-fh-netdevice: ''
    ran.openshift.io/oran-mh-vfio: ''    
    ran.openshift.io/oran-mh-netdevice: ''
  node_annotations:
    kubernetes.io/description: 'test annotation du_001'
  # IP will be applied to either the bond interface (if enabled) or the 1st interface in the "interfaces" list
  IP: "10.198.7.168"
  prefix_length: 26
  #Assumes 1st "bond_members" interface(s) in "interface list" forms the bond
  bond_enable: "false"
  bond_name: bond0
  bond_members: "2"
  bond_mode: active-backup
  #
  int_mtu: 9000
  #
  interfaces:
  - name: "ens4f0"
    mac: "3c:fd:fe:b4:d3:e4"
  - name: "ens4f1"
    mac: "3c:fd:fe:b4:d3:e5"
  - name: "eno1"
    mac: "7c:d3:0a:66:0c:c8"
  - name: "eno2"
    mac: "7c:d3:0a:66:0c:c9"
  - name: "eno3"
    mac: "7c:d3:0a:66:0c:ca"
  - name: "eno4"
    mac: "7c:d3:0a:66:0c:cb"
  bmc_username: USERID
  bmc_password: PASSW0RD
  bmc_address: redfish-virtualmedia+https://10.198.0.66/redfish/v1/Systems/1
