---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  config:
    env:
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: openshift-gitops, {{ $.Values.gitops.namespace }}
  channel: "stable"
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  # Modify source name of the catalogsource for isolated network deployments
  source: {{ coalesce $.Values.cluster.operator_source $.Values.quay.operator_source }}
  sourceNamespace: openshift-marketplace
