---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: postinstall-{{ $.Values.cluster.name }}-add-registry-ca-wait-job
  namespace: {{ $.Values.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.gitops.service_account }}
      serviceAccountName: {{ $.Values.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.cluster.name }}-add-registry-ca-wait-job
          env:
            - name: SLEEP
              value: "3"
          command:
            - /bin/bash
            - -c
            - |
              echo "Adding local CA to the global one."
              CONFIG_MAP="Pausing $SLEEP seconds..."
              while [ "$CONFIG_MAP" != "registry-ca-local" ]; do
                echo "Waiting for the CA ConfigMap to be defined. ($CONFIG_MAP)"
                sleep $SLEEP
                CONFIG_MAP=$( oc get ConfigMap -n openshift-config registry-ca-local -o jsonpath={..metadata.name} )
              done
              # Add it to the  additionalTrustedCA
              oc patch image.config.openshift.io/cluster --patch '{"spec":{"additionalTrustedCA":{"name":"registry-ca-local"}}}' --type=merge
              #
              echo "Adding local pull secret to the global one."
              cd /tmp
              oc extract secret/pull-secret -n openshift-config --confirm
              cat .dockerconfigjson | \
                  jq --compact-output '.auths["{{ $.Values.ai.registry_url }}/{{ $.Values.ai.registry_user }}"] |= . + {"auth":"{{ printf "%s:%s" $.Values.ai.registry_user $.Values.ai.registry_password | b64enc  }}"}' \
                  > new_dockerconfigjson
              oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=new_dockerconfigjson
              rm -f .dockerconfigjson new_dockerconfigjson
              echo "All done! Hooray!"
