---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.cluster.name }}-wait-{{ $.Values.node.name }}-label-annotate-job
  namespace: {{ $.Values.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      containers:
        - image: {{ $.Values.gitops.hook_image }}
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.cluster.name }}-{{ $.Values.node.name }}-wait-ready-label-annotate-job
          env:
            - name: SLEEP
              value: "15"
          command:
            - /bin/bash
            - -c
            - |
              echo "Cluster Pre Install Hook"
              URL_READY="Pausing $SLEEP seconds..."
              CSV_STATUS="Pausing $SLEEP seconds..."
              while [ "$CSV_STATUS" != "Ready" ]; do
                echo "Waiting for worker {{ $.Values.node.name }} to be ready. ($CSV_STATUS)"
                sleep $SLEEP
                CSV_STATUS=$( oc get nodes | egrep {{ $.Values.node.name }} | awk '{print $2}' )
              done
              # Labels
              {{- range $key, $key_value := $.Values.node.node_labels }}
                {{- if eq $key_value "" }}  
              oc label node {{ $.Values.node.name }} {{ $key }}={{ $key_value | squote }}
              {{- else }}
              oc label node {{ $.Values.node.name }} {{ $key }}={{ $key_value }}
                {{- end }}
              {{- end }}
              {{- if eq $.Values.node.ocs "true" }}
              oc label node {{ $.Values.node.name }} cluster.ocs.openshift.io/openshift-storage=''
              {{- end }}
              {{- if eq $.Values.node.lso "true" }}
              oc label node {{ $.Values.node.name }} ran.openshift.io/lso=''
              {{- end }}
              # Annotations
              {{- range $key, $key_value := $.Values.node.node_annotations }}
                {{- if eq (toString $key_value) "" }}  
              oc annotate node {{ $.Values.node.name }} {{ $key }}={{ $key_value | squote }}
              {{- else }}
                {{- if (regexFind " " $key_value) }}
              oc annotate node {{ $.Values.node.name }} {{ $key }}={{ $key_value | squote }}
              {{- else }}
              oc annotate node {{ $.Values.node.name }} {{ $key }}={{ $key_value }}
                  {{- end }}
                {{- end }}
              {{- end }}
              echo "All done! Hooray!"
